CREATE TABLE Doctor(
	DOCTOR_ID	    CHAR(15)		NOT NULL,
	DOCTOR_NAME	    CHAR(10),
	HOSPITAL	    CHAR(20),
	DOCTOR_AGE	    DATE,			
    LICENSE         INTEGER,
    PRIMARY KEY     (DOCTOR_ID)	
);
CREATE TABLE PATIENT(
   PATIENT_ID       char(15)      NOT NULL,
   PATIENT_NAME     char(10),
   PATIENT_SEX      char(6),
   PATIENT_AGE      DATE,         
   DOCTOR_ID       char(15),
   PRIMARY KEY (PATIENT_ID),
   FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR (DOCTOR_ID)
);
CREATE TABLE EXERCISE(
    E_KIND          CHAR(10),/*primary key*/
    PATIENT_ID       CHAR(15),
    CALORIE         INTEGER,
    E_DATE          DATE,
    E_TIME          INTEGER,  
    CONSTRAINT exercies_pid_fk FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (PATIENT_ID) on delete cascade,
    PRIMARY KEY (PATIENT_ID)
);

CREATE TABLE FOOD(
    E_NAME          CHAR(10),/*primary key*/
   PATIENT_ID       CHAR(15)    NOT NULL,
    SUGAR           INTEGER,
    NATRIUM         INTEGER,
    FAT             INTEGER,
    F_DATE          DATE,
    constraint food_pid_fk FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (PATIENT_ID) on delete cascade,
    PRIMARY KEY (PATIENT_ID)
);

CREATE TABLE LIFESTYLE(
   PATIENT_ID       CHAR(15),
    SMOKE           INTEGER,
    DRINKING        INTEGER,
    SLEEP           INTEGER,
    L_DATE          DATE,
    constraint lifestyle_pid_fk FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (PATIENT_ID) on delete cascade,
    PRIMARY KEY (PATIENT_ID)
);

DESC DOCTOR;
DROP TABLE EXERCISE;
DROP TABLE FOOD;
DROP TABLE LIFESTYLE;
DROP TABLE PATIENT;
DROP TABLE DOCTOR;


/*
    DOCTOR_ID	    VARCHAR2(15)		NOT NULL,
	DOCTOR_NAME	    VARCHAR2(10),
	HOSPITAL	    VARCHAR2(20),
	DOCTOR_AGE	    DATE,			
    LICENSE         INTEGER,
    PRIMARY KEY     (DOCTOR_ID)	
*/

INSERT INTO DOCTOR (DOCTOR_ID, DOCTOR_NAME, HOSPITAL, DOCTOR_AGE, LICENSE)
VALUES ('jh4049','김정호','신촌세브란스병원',TO_DATE('10-04-1983','MM-DD-YYYY'),281321);
/**/
INSERT INTO DOCTOR (DOCTOR_ID, DOCTOR_NAME, HOSPITAL, DOCTOR_AGE, LICENSE)
VALUES ('hg2312','장호근','명지성모병원',TO_DATE('04-18-1987','MM-DD-YYYY'),283172);
/**/
INSERT INTO DOCTOR (DOCTOR_ID, DOCTOR_NAME, HOSPITAL, DOCTOR_AGE, LICENSE)
VALUES ('js2287','임지수','주례참조은의원',TO_DATE('06-11-1979','MM-DD-YYYY'),280412);
/**/
INSERT INTO DOCTOR (DOCTOR_ID, DOCTOR_NAME, HOSPITAL, DOCTOR_AGE, LICENSE)
VALUES ('sw4049','장시원','장시원내과',TO_DATE('10-04-1983','MM-DD-YYYY'),287121);
/**/
INSERT INTO DOCTOR (DOCTOR_ID, DOCTOR_NAME, HOSPITAL, DOCTOR_AGE, LICENSE)
VALUES ('wj3267','이원준','선내과의원',TO_DATE('06-01-1996','MM-DD-YYYY'),282819);
/**/
INSERT INTO DOCTOR (DOCTOR_ID, DOCTOR_NAME, HOSPITAL, DOCTOR_AGE, LICENSE)
VALUES ('bg3266','이병길','가야제일의원',TO_DATE('05-28-1996','MM-DD-YYYY'),285123);
/**/
INSERT INTO DOCTOR (DOCTOR_ID, DOCTOR_NAME, HOSPITAL, DOCTOR_AGE, LICENSE)
VALUES ('dh3245','김덕훈','고운하늘의원',TO_DATE('03-10-1996','MM-DD-YYYY'),281111);
/*----------------------------------------------------------------------------------------------------*/
/*
    PATIENT_ID	    VARCHAR2(10)		NOT NULL,
	PATIENT_NAME	VARCHAR2(10),
	PATIENT_SEX	    VARCHAR2(4),
	PATIENT_AGE	    DATE,			
	DOCTOR_ID	    VARCHAR2(10),
    PRIMARY KEY (PATIENT_ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR (DOCTOR_ID)
*/
SELECT * FROM patient;
INSERT INTO patient (PATIENT_ID, PATIENT_NAME, PATIENT_SEX, PATIENT_AGE, DOCTOR_ID)
VALUES ('cm1109','김창민','남성',TO_DATE('12-21-1993','MM-DD-YYYY'),'jh4049');

INSERT INTO patient (PATIENT_ID, PATIENT_NAME, PATIENT_SEX, PATIENT_AGE, DOCTOR_ID)
VALUES ('ya2220','김연아','여성',TO_DATE('10-04-1961','MM-DD-YYYY'),'hg2312');

INSERT INTO patient (PATIENT_ID, PATIENT_NAME, PATIENT_SEX, PATIENT_AGE, DOCTOR_ID)
VALUES ('eh6918','박은하','여성',TO_DATE('01-01-2000','MM-DD-YYYY'),'hg2312');

INSERT INTO patient (PATIENT_ID, PATIENT_NAME, PATIENT_SEX, PATIENT_AGE, DOCTOR_ID)
VALUES ('sh9882','하상후','남성',TO_DATE('07-31-1982','MM-DD-YYYY'),'wj3267');

INSERT INTO patient (PATIENT_ID, PATIENT_NAME, PATIENT_SEX, PATIENT_AGE, DOCTOR_ID)
VALUES ('jh1928','강지호','남성',TO_DATE('08-05-1999','MM-DD-YYYY'),'dh3245');

INSERT INTO patient (PATIENT_ID, PATIENT_NAME, PATIENT_SEX, PATIENT_AGE, DOCTOR_ID)
VALUES ('jh4412','안제희','여성',TO_DATE('05-05-1983','MM-DD-YYYY'),'js2287');

INSERT INTO patient (PATIENT_ID, PATIENT_NAME, PATIENT_SEX, PATIENT_AGE, DOCTOR_ID)
VALUES ('cm1231','김창민','남성',TO_DATE('09-12-1993','MM-DD-YYYY'),'sw4049');

INSERT INTO patient (PATIENT_ID, PATIENT_NAME, PATIENT_SEX, PATIENT_AGE, DOCTOR_ID)
VALUES ('kh4049','오기훈','남성',TO_DATE('03-18-1973','MM-DD-YYYY'),'bg3266');

commit;

select * from doctor;